application: wwphssinfo
version: 2018
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /static
  static_dir: staticfiles/

- url: .*
  script: WWPHSSinfo.wsgi.application

- url: /_ah/(mapreduce|queue|warmup).*
  script: WWPHSSinfo.wsgi.application
  login: admin


libraries:
- name: django
  version: "1.11"

- name: ssl
  version: latest


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
#- ^*.sqlite3$

